interface WatermarkProps {
  type: 'bill' | 'purchase' | 'challan';
}

export function Watermark({ type }: WatermarkProps) {
  const documentType =
    type === 'bill' ? 'Bill' : type === 'purchase' ? 'Purchase' : 'Challan';

  return (
    <div className="watermark">
      <p className="text-sm font-semibold">
        <b>BusinessPlus Free Version </b><br /><b>{documentType} Generated by BusinessPlus</b>
      </p>

      <style>{`
        .watermark {
          position: fixed;
          bottom: 25mm;
          left: 50%;
          transform: translateX(-50%);
          text-align: center;
          opacity: 0.6;
          font-size: 12px;
          color: #555;
          z-index: 9999;
          pointer-events: none;
        }

        @media print {
          .watermark {
            position: fixed;
            bottom: 60mm;
          }
        }

        @media screen {
          .watermark {
            display: none;
          }
        }
      `}</style>
    </div>
  );
}